import { ExpenseLogForm } from '@/components/dashboard/expense-tracking/expense-log-form';
import { ExpenseTable } from '@/components/dashboard/expense-tracking/expense-table';

const dummyData = [
  {
    id: '1',
    tranDate: new Date('2024-06-01'),
    supplierId: 'sup-1',
    supplierName: 'Supplier One',
    employeeName: 'John Doe',
    itemId: 'item-1',
    itemName: 'Item One',
    quantity: 10,
    amount: 100.0,
    invoice: 1001,
    paymentType: 'Credit Card',
    paymentStatus: 'Paid',
    comment: 'No issues',
    employeeId: '',
  },
  {
    id: '2',
    tranDate: new Date('2024-06-02'),
    supplierId: 'sup-2',
    supplierName: 'Supplier Two',
    employeeName: 'Jane Smith',
    itemId: 'item-2',
    itemName: 'Item Two',
    quantity: 5,
    amount: 50.0,
    invoice: 1002,
    paymentType: 'Cash',
    paymentStatus: 'Pending',
    comment: 'Pending payment',
    employeeId: '',
  },
  {
    id: '3',
    tranDate: new Date('2024-06-03'),
    supplierId: 'sup-3',
    supplierName: 'Supplier Three',
    employeeName: 'Alice Johnson',
    itemId: 'item-3',
    itemName: 'Item Three',
    quantity: 20,
    amount: 200.0,
    invoice: 1003,
    paymentType: 'Bank Transfer',
    paymentStatus: 'Paid',
    comment: '',
    employeeId: '',
  },
  // {
  //   id: '4',
  //   tranDate: new Date('2024-06-04'),
  //   supplierId: 'sup-4',
  //   supplierName: 'Supplier Four',
  //   employeeName: 'Bob Brown',
  //   itemId: 'item-4',
  //   itemName: 'Item Four',
  //   quantity: 15,
  //   amount: 150.0,
  //   invoice: 1004,
  //   paymentType: 'Credit Card',
  //   paymentStatus: 'Overpaid',
  //   comment: 'Refund issued',
  // },
  // {
  //   id: '5',
  //   tranDate: new Date('2024-06-05'),
  //   supplierId: 'sup-5',
  //   supplierName: 'Supplier Five',
  //   employeeName: 'Carol White',
  //   itemId: 'item-5',
  //   itemName: 'Item Five',
  //   quantity: 8,
  //   amount: 80.0,
  //   invoice: 1005,
  //   paymentType: 'Cash',
  //   paymentStatus: 'Paid',
  //   comment: '',
  // },
  // {
  //   id: '6',
  //   tranDate: new Date('2024-06-06'),
  //   supplierId: 'sup-6',
  //   supplierName: 'Supplier Six',
  //   employeeName: 'David Green',
  //   itemId: 'item-6',
  //   itemName: 'Item Six',
  //   quantity: 12,
  //   amount: 120.0,
  //   invoice: 1006,
  //   paymentType: 'Bank Transfer',
  //   paymentStatus: 'Pending',
  //   comment: 'Awaiting confirmation',
  // },
  // {
  //   id: '7',
  //   tranDate: new Date('2024-06-07'),
  //   supplierId: 'sup-7',
  //   supplierName: 'Supplier Seven',
  //   employeeName: 'Eva Black',
  //   itemId: 'item-7',
  //   itemName: 'Item Seven',
  //   quantity: 30,
  //   amount: 300.0,
  //   invoice: 1007,
  //   paymentType: 'Credit Card',
  //   paymentStatus: 'Paid',
  //   comment: '',
  // },
  // {
  //   id: '8',
  //   tranDate: new Date('2024-06-08'),
  //   supplierId: 'sup-8',
  //   supplierName: 'Supplier Eight',
  //   employeeName: 'Frank Blue',
  //   itemId: 'item-8',
  //   itemName: 'Item Eight',
  //   quantity: 7,
  //   amount: 70.0,
  //   invoice: 1008,
  //   paymentType: 'Cash',
  //   paymentStatus: 'Overpaid',
  //   comment: 'Credit note issued',
  // },
  // {
  //   id: '9',
  //   tranDate: new Date('2024-06-09'),
  //   supplierId: 'sup-9',
  //   supplierName: 'Supplier Nine',
  //   employeeName: 'Grace Red',
  //   itemId: 'item-9',
  //   itemName: 'Item Nine',
  //   quantity: 18,
  //   amount: 180.0,
  //   invoice: 1009,
  //   paymentType: 'Bank Transfer',
  //   paymentStatus: 'Pending',
  //   comment: 'Waiting for bank confirmation',
  // },
  // {
  //   id: '10',
  //   tranDate: new Date('2024-06-10'),
  //   supplierId: 'sup-10',
  //   supplierName: 'Supplier Ten',
  //   employeeName: 'Harry Yellow',
  //   itemId: 'item-10',
  //   itemName: 'Item Ten',
  //   quantity: 25,
  //   amount: 250.0,
  //   invoice: 1010,
  //   paymentType: 'Credit Card',
  //   paymentStatus: 'Paid',
  //   comment: '',
  // },
];

export default function ExpenseTrackingPage() {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl">Add expense</h1>
      <ExpenseLogForm data={dummyData} />
    </div>
  );
}
